[build.environment]
  NPM_VERSION = "6.13.4"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[dev]
  command = "npm run start"
  targetPort = 8888

[[redirects]]
  from = "/projects"
  to = "/collections/#filter=.personal"
  status = 301

[[redirects]]
  from = "/posts/*"
  to = "/#blog-:splat"
  status = 301

  [[redirects]]
  from = "/portfolio"
  to = "/collections/"
  status = 301